# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "Build-1941" ]
  pull_request:
    branches: [ "Build-1941" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: action/checkout@v2
    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bibhuti123/dotnet:$(date +%s)
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/dotnet
      
