# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "Build-1941" ]
  pull_request:
    branches: [ "Build-1941" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Get commit count
      id: commit_count
      run: |
        COMMIT_COUNT=$(git rev-list --count HEAD)
        echo "::set-output name=COMMIT_COUNT::$COMMIT_COUNT" 
        
    - name: Build the Docker image
      run: |
        COMMIT_COUNT=$(echo ${{ steps.commit_count.outputs.COMMIT_COUNT }})
        docker build . --file Dockerfile --tag bibhuti123/dotnet:$COMMIT_COUNT
        
    - name: Tag the Docker image with latest
      run: |
        docker tag bibhuti123/dotnet:$VERSION bibhuti123/dotnet:latest
      env:
        VERSION: ${{ steps.env.outputs.VERSION }}
          
    - name: Docker push
      run: |
        COMMIT_COUNT=$(echo ${{ steps.commit_count.outputs.COMMIT_COUNT }})
        docker push bibhuti123/dotnet:$COMMIT_COUNT
